plan: free

services:
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/Sujay-22/Smart-AI-Agent.git
    healthCheckPath: /health
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sra_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

  - type: static_site
    name: frontend
    repo: https://github.com/Sujay-22/Smart-AI-Agent.git
    buildCommand: "npm --prefix frontend install && npm --prefix frontend run build"
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: backend
          property: url

databases:
  - name: sra_db
    plan: free
